# Generated by Django 5.0.7 on 2024-08-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.IntegerField()),
                ('phone_number', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=100)),
                ('delivery_address', models.TextField()),
                ('password_hash', models.CharField(max_length=256)),
            ],
        ),
    ]
